---
title: "adaptive-introgression"
output: html_document
---

"If a haplotype was introduced by introgression from archaic humans, the reason for its continued survival in present-day humans may be that it was affected by positive selection or balancing selection, or that it was not removed from the population by negative selection or genetic drift. Distinguishing between these hypotheses requires additional statistical analyses, because when a genomic region contains introgressed DNA, the pattern of polymorphism may be different than expected under a neutral model with no introgression. As mentioned previously, in regions with introgressed DNA, the haplotype structure will change, there will be an increase in LD, and the distribution of allele frequencies will change from that expected without introgression. These patterns are exactly the signals that many standard methods for detecting selection employ. These include the Integrated Haplotype Score (iHS), Extended Haplotype Homozygosity (EHH), Cross-Population Extended Haplotype Homozygosity (XP-EHH), Tajima’s D, Fay and Wu’s H, Composite of Multiple Signals (CMS), Fst, or variations on Fst such as the Locus Specific Branch Length (LSBL) or the Population Branch Statistic (PBS). Naïve use of these methods can therefore easily lead to false inferences of selection as the pattern generated by introgression alone may be incorrectly interpreted as evidence of selection." [1]

[1] Racimo, F., Sankararaman, S., Nielsen, R., & Huerta-Sánchez, E. (2015). Evidence for archaic adaptive introgression in humans. Nature Reviews Genetics, 16(6), 359-371.
